# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for your backend
  payment:
    restart: unless-stopped
    healthcheck:
      test: >
        curl -f -X GET http://localhost:8080/health || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    build:
      context: ./
      target: production
    environment:
      DATABASE_URI: mongodb://payment-db:27017
      DATABASE_NAME: misarch
      SIMULATION_URL: http://simulation:8080
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
      OTEL_NODE_RESOURCE_DETECTORS: env,host,os
      OTEL_SERVICE_NAME: payment
      OTEL_SEMCONV_STABILITY_OPT_IN: http
      NODE_OPTIONS: --require @opentelemetry/auto-instrumentations-node/register
    depends_on:
      - payment-db
  payment-db:
    image: mongo:6.0
    hostname: payment-db
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    volumes:
      - payment-db-data:/data/db
  payment-dapr:
    image: "daprio/daprd:edge"
    network_mode: "service:payment"
    command:
      [
        "./daprd",
        "--app-id",
        "payment",
        "--app-port",
        "${EXPERIMENT_CONFIG_SIDECAR_PORT:-8080}",
        "--dapr-http-port",
        "3500",
        "-placement-host-address",
        "placement:50006",
        "--config",
        "/config.yaml",
        "--resources-path",
        "/components",
      ]

volumes:
  payment-db-data:
