name: Update GraphQL schema

on:
  push:
    branches:
      - main

jobs:
  schema:
    name: Update GraphQL schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: "misarch/schemas"
          path: "schemas"
      - name: Save graphql schemas
        uses: misarch/graphql-schema-transform@v1
        with:
          schema: src/payment.gql
          target: schemas/payment.graphql
      - uses: peter-evans/create-pull-request@v5
        with:
          path: ./schemas
          commit-message: Update payment schema
          branch: update/payment
          token: ${{ secrets.SCHEMAS_PUSH_SECRET }}